### ISSUE TITLE
Cant put in Full Screen while watching streaming services

### ISSUE THREAD

**Issue by puppinoo** [Meli10/Rocket-Browser#4]
**Describe the bug**
Cant put in Fullscreen mode while streaming

**To Reproduce**
Open a stream from one of the mainstream services (I treid with Paramountplus.com US
1. Go to www.paramountplus.com
2. Click on on of the many available streams
3. Click in the icon sown on the right to put the video in fullscreen

**Expected behavior**
Video in Full Screen.

**Desktop (please complete the following information):**
 - OS:  Ubuntu 23.10
 - Browser this one
 - Version Latest

Thanks.

**Comment by Meli10** [comment]
I was able to successfully enable full screen mode while watching videos on this web engine. To exit full screen you will just need to click ESC on your keyboard. Although before I compile everything into the application, I want to see if I can fix the leaking memory issue. It seems doable, I just don't think anyone making a web engine with QT has considered testing the memory.

**Comment by Meli10** [comment]
Issue has been fixed. See Latest Rocket Release.
